name: Fetch Real-Time Price

on:
  schedule:
    - cron: '*/30 1-6 * * 1-5' # 週一到週五，UTC 1:00-6:00 (台灣時間 9:00-14:00) 每30分鐘
    - cron: '0 0,7-23 * * 1-5' # 週一到週五，其他時間每小時
    - cron: '0 * * * 0,6' # 週六和週日，每小時
  repository_dispatch:
    types: [trigger-fetch-real-time-price]
  workflow_dispatch: # 允許手動觸發

jobs:
  fetch-real-time-price:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Real-Time Price
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
        run: |
          response=$(curl -X POST \
               -H "x-api-key: $X_API_KEY" \
               -H "Content-Type: application/json" \
               -w "\n%{http_code}" \
               --max-time 20 \
               https://jackson-tseng.vercel.app/api/updateRealTimePrice)
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          echo "Status code: $status_code"
          echo "Response body: $body"
          if [ "$status_code" -ne 200 ]; then
            echo "API call to update real-time prices failed"
            exit 1
          fi
