name: Update Stock Data

on:
  schedule:
    - cron: '0 */2 * * *' # 每兩小時執行一次
  workflow_dispatch: # 允許手動觸發

permissions:
  contents: write
  actions: write

jobs:
  update-stock-data:
    runs-on: ubuntu-latest
    steps:
      - name: Update Stocks Data
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
        run: |
          response=$(curl -X POST \
               -H "x-api-key: $X_API_KEY" \
               -H "Content-Type: application/json" \
               -w "\n%{http_code}" \
               --max-time 300 \
               https://jackson-tseng.vercel.app/api/updateStocks)
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          echo "Status code: $status_code"
          echo "Response body: $body"
          if [ "$status_code" -ne 200 ]; then
            echo "API call to update stocks failed"
            exit 1
          fi

      - name: Wait for 3 seconds
        run: sleep 3

      - name: Trigger fetchRealTimePrice workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-fetch-real-time-price
